### ISSUE TITLE
AttributeError: Sequence object has no attribute asOctets

### ISSUE THREAD

**Issue by jsjolund** [louisabraham/ffpass#49] opened 2020-01-30 20:43 UTC
Hi, when I try to import password CSV from Chromium I get the following error:
```
$ ffpass import --from pw.csv
Traceback (most recent call last):
  File "/usr/bin/ffpass", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/ffpass/__init__.py", line 354, in main
    args.func(args)
  File "/usr/lib/python3.8/site-packages/ffpass/__init__.py", line 287, in main_import
    key = askpass(args.directory)
  File "/usr/lib/python3.8/site-packages/ffpass/__init__.py", line 254, in askpass
    key = getKey(directory, password)
  File "/usr/lib/python3.8/site-packages/ffpass/__init__.py", line 93, in getKey
    entrySalt = decodedA11[0][1][0].asOctets()
AttributeError: 'Sequence' object has no attribute 'asOctets'
```
I am using Arch Linux with `Python 3.8.1`, `pyasn1 0.4.8`, and `ffpass 0.4.8`.

**Comment by louisabraham** [comment] 2020-01-31 14:17
Could you modify the code to add lines

```
print(1, a11)
print(2, decodedA11)
print(3, decodedA11[0][1][0])
```

before the error?

Also, this error might happen if the firefox database is empty/malformed. Try to add one password manually in Firefox.

**Comment by jsjolund** [comment] 2020-02-01 10:40
Thanks. I tried adding a password, but got the same error. Here is the output
```
1 b'0\x81\x910m\x06\t*\x86H\x86\xf7\r\x01\x05\r0`0A\x06\t*\x86H\x86\xf7\r\x01\x05\x0c04\x04 :\xd3\x98G26\xb1>>\x9a\xd6\x9e$n\xa9\xd06\x1ed~O\xdc<W\xc8\xa0\x01e\xd2o\x0bM\x02\x01\x01\x02\x01 0\n\x06\x08*\x86H\x86\xf7\r\x02\t0\x1b\x06\t`\x86H\x01e\x03\x04\x01*\x04\x0e\xfa)\xdd\x93\x95Fy\x94^{\x92\x114\x8b\x04 \xd6\x94\xe58jQ\xf3\xcf\xae\xea\x9b\xab8\xd6\xefK\xf7IA\xa0I\xa8\xefT\xef\xd4\xfci\xc1"\xc4B'
2 Sequence:
 field-0=Sequence:
  field-0=1.2.840.113549.1.5.13
  field-1=SequenceOf:
   Sequence:
    field-0=1.2.840.113549.1.5.12
    field-1=Sequence:
     field-0=0x3ad398473236b13e3e9ad69e246ea9d0361e647e4fdc3c57c8a00165d26f0b4d
     field-1=1
     field-2=32
     field-3=SequenceOf:
      1.2.840.113549.2.9

   Sequence:
    field-0=2.16.840.1.101.3.4.1.42
    field-1=0xfa29dd93954679945e7b9211348b


 field-1=0xd694e5386a51f3cfaeea9bab38d6ef4bf74941a049a8ef54efd4fc69c122c442

3 Sequence:
 field-0=1.2.840.113549.1.5.12
 field-1=Sequence:
  field-0=0x3ad398473236b13e3e9ad69e246ea9d0361e647e4fdc3c57c8a00165d26f0b4d
  field-1=1
  field-2=32
  field-3=SequenceOf:
   1.2.840.113549.2.9

Traceback (most recent call last):
  File "/usr/bin/ffpass", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/ffpass/__init__.py", line 357, in main
    args.func(args)
  File "/usr/lib/python3.8/site-packages/ffpass/__init__.py", line 290, in main_import
    key = askpass(args.directory)
  File "/usr/lib/python3.8/site-packages/ffpass/__init__.py", line 257, in askpass
    key = getKey(directory, password)
  File "/usr/lib/python3.8/site-packages/ffpass/__init__.py", line 96, in getKey
    entrySalt = decodedA11[0][1][0].asOctets()
AttributeError: 'Sequence' object has no attribute 'asOctets'
```
I then tried deleting my firefox profile and creating a new one with one stored password. This resulted in ffpass not finding the profile directory automatically. I used the `-d` option and got an error a few rows earlier.
```
ffpass import --from pw.csv -d /home/user/.mozilla/firefox/7djkomgr.default-release
Traceback (most recent call last):
  File "/usr/bin/ffpass", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/ffpass/__init__.py", line 357, in main
    args.func(args)
  File "/usr/lib/python3.8/site-packages/ffpass/__init__.py", line 290, in main_import
    key = askpass(args.directory)
  File "/usr/lib/python3.8/site-packages/ffpass/__init__.py", line 257, in askpass
    key = getKey(directory, password)
  File "/usr/lib/python3.8/site-packages/ffpass/__init__.py", line 74, in getKey
    entrySalt = decodedItem2[0][1][0].asOctets()
AttributeError: 'Sequence' object has no attribute 'asOctets'
```
Adding those lines
```
print(1, item2)
print(2, decodedItem2)
print(3, decodedItem2[0][1][0])
```
Outputted this
```
1 b'0\x81\x810m\x06\t*\x86H\x86\xf7\r\x01\x05\r0`0A\x06\t*\x86H\x86\xf7\r\x01\x05\x0c04\x04 \xd0\xe0\xd3\x1c\xae6\\\xbf\r\xd7\\\xbe>@\x17\x03\x80n\xa9\xbc[R\xdb\xf9\xac\x89=\x8c\xa9\xd0\x15v\x02\x01\x01\x02\x01 0\n\x06\x08*\x86H\x86\xf7\r\x02\t0\x1b\x06\t`\x86H\x01e\x03\x04\x01*\x04\x0e\xbdzT3\xb5\x11\x1a(\xc9\xf2I\xb2\x13\x7f\x04\x10]\xafZ&s\x17\x1b\xcf\xc4\x1f_\r\x1d\x82k '
2 Sequence:
 field-0=Sequence:
  field-0=1.2.840.113549.1.5.13
  field-1=SequenceOf:
   Sequence:
    field-0=1.2.840.113549.1.5.12
    field-1=Sequence:
     field-0=0xd0e0d31cae365cbf0dd75cbe3e401703806ea9bc5b52dbf9ac893d8ca9d01576
     field-1=1
     field-2=32
     field-3=SequenceOf:
      1.2.840.113549.2.9

   Sequence:
    field-0=2.16.840.1.101.3.4.1.42
    field-1=0xbd7a5433b5111a28c9f249b2137f


 field-1=0x5daf5a2673171bcfc41f5f0d1d826b20

3 Sequence:
 field-0=1.2.840.113549.1.5.12
 field-1=Sequence:
  field-0=0xd0e0d31cae365cbf0dd75cbe3e401703806ea9bc5b52dbf9ac893d8ca9d01576
  field-1=1
  field-2=32
  field-3=SequenceOf:
   1.2.840.113549.2.9
```

**Comment by ognone** [comment] 2020-02-07 19:43
same error for me, also Arch

**Comment by louisabraham** [comment] 2020-02-07 20:07
What version of Firefox are you using? It might be caused by a recent update.

**Comment by ognone** [comment] 2020-02-07 20:16
FF 72.0.2

**Comment by ognone** [comment] 2020-02-10 19:24
@louisabraham And you (which Firefox)?

**Comment by jsjolund** [comment] 2020-02-10 20:18
Like ognone I am also using Firefox 72.0.2

**Comment by louisabraham** [comment] 2020-02-10 21:45
I'm using 72.0.2 without any issue but my passwords were already saved in previous versions of FF so it might be a bug with new password files.

**Comment by ognone** [comment] 2020-02-12 17:19
What should I do now? After downgrading FF it refuses to use the old profile.

**Comment by louisabraham** [comment] 2020-02-13 23:33
Hi, bad news: it appears that FF is now using pbes2 (http://oid-info.com/get/1.2.840.113549.1.5.13) to encode your passwords instead of pbeWithSha1AndTripleDES-CBC that is still used on my computer.

It's quite complicated to implement that new encryption. Actually, reverse engineering the previous encryption was the hardest part of making `ffpass`.

I didn't find any python implementation of pbes2 or simple description that could help me.
Furthermore, even if I had those and a free afternoon, I cannot even force Firefox to use pbes2 so I don't even see how I could test.

Another possibility is that your passwords are still encrypted with pbeWithSha1AndTripleDES-CBC but FF changed the location of the key.

**Comment by mnoorenberghe** [comment] 2020-02-13 23:44
See https://bugzilla.mozilla.org/show_bug.cgi?id=1585189 and https://bugzilla.mozilla.org/show_bug.cgi?id=1562671

**Comment by arian81** [comment] 2020-03-24 15:57
I have the same problem on Manjaro and if there's no fix for that well it runs the whole programme obsolete

**Comment by louisabraham** [comment] 2020-03-26 08:51
There is hope, I found an implementation of PBES2: https://github.com/Legrandin/pycryptodome/blob/master/lib/Crypto/IO/_PBES.py

I should manage to hack a fix as soon as I have free time :)

**Comment by louisabraham** [comment] 2020-03-27 01:49
Small update: I tried to decrypt the PBES values in key4.db (item2 and a11). My main issue is that the IV provided for aes256-CBC have 14 bytes instead of the 16 required. I tried appending or prepending 2 bruteforced bytes without success.

**Comment by louisabraham** [comment] 2020-03-27 02:18
The explanation about the 14 bytes is here https://hg.mozilla.org/projects/nss/rev/fc636973ad06392d11597620b602779b4af312f6#l6.49

However, I tried prepending `b'\x04\x0e'` to DER-encode without success.

**Comment by louisabraham** [comment] 2020-03-30 12:04
A lead to investigate is the use of the nss library like https://github.com/unode/firefox_decrypt

**Comment by mnoorenberghe** [comment] 2020-04-18 06:16
firepwd has a fix now that you may be able to port: https://github.com/lclevy/firepwd/commit/4981e8dd4cc29ea05bcb2eb36d78d3113b207834

**Comment by Icy-Thought** [comment] 2020-04-22 21:28
Looking forward to the upcoming update of the following package! Having 600+ passwords stacked in Google Chrome feels rather odd if one has not been a Chrome user for quite some time.

Nonetheless, thank you for putting in all the effort required to resolve the issue we are presented with today! :)

**Comment by joksik** [comment] 2020-05-06 15:38
any news about new release ffpass ??

**Comment by thinkpadder1** [comment] 2020-06-05 03:42
I managed to do a workaround:

## Workaround

1. Install Firefox 70
2. Launch it and disable automatic updates.
3. Put in a bogus user/pass to initialize the database then close the browser
4. Import via ffpass with the --dir option
5. Launch browser
6. Sign into Firefox Sync
7. You can uncheck all the sync checkboxes except for password
8. Let it sync (hit Sync Now to be sure)
9. Close browser
10. Open your latest Firefox
11. Sign into Firefox Sync if you haven't
12. Let it sync
13. It works :tada: 
14. Delete Firefox 70

**Comment by raphaelchinchilla** [comment] 2020-07-18 20:09
Has there been any success on fixing this problem besides the workaround above ?

**Comment by evertonstz** [comment] 2020-07-19 15:18
> Has there been any success on fixing this problem besides the workaround above ?

I think your best chance now is using firefox nightly, they've implemented imports and exports straight into the vault.

**Comment by mnoorenberghe** [comment] 2020-07-19 17:54
Firefox Beta 79 has export and it will be in regular Firefox late next week. Import will probably only be in Fx81.

**Comment by slava-nat** [comment] 2020-07-21 08:54
> I managed to do a workaround:
> ## Workaround
> 
>     1. Install Firefox 70
> 
>     2. Launch it and disable automatic updates.
> 
>     3. Put in a bogus user/pass to initialize the database then close the browser
> 
>     4. Import via ffpass with the --dir option
> 
>     5. Launch browser
> 
>     6. Sign into Firefox Sync
> 
>     7. You can uncheck all the sync checkboxes except for password
> 
>     8. Let it sync (hit Sync Now to be sure)
> 
>     9. Close browser
> 
>     10. Open your latest Firefox
> 
>     11. Sign into Firefox Sync if you haven't
> 
>     12. Let it sync
> 
>     13. It works tada
> 
>     14. Delete Firefox 70

Thanks a lot! That's worked for me.
By the way, the directory of your firefox 70 profile needed for the `--dir` option can be found directly in the browser: `Help`->`Troubleshooting information`->`Profile Directory`.

**Comment by louisabraham** [comment] 2021-01-30 23:28
Hi, I think it is solved in the latest version (don't thank me, thank @lmcclell who did everything).

**Closed by louisabraham** 2021-01-30 23:28 UTC
